Repository qonto/ember-phone-input, pull requests merged in 2018-12, with the labels that each got.

#10 Upgrade devDependencies
  yarn.lock
Labels: dependencies

#11 Update .eslintrc.js
  .eslintrc.js
  config/addon-docs.js
  config/deploy.js
Labels: internal

#12 Create a country attribute
  addon/components/phone-input.js
  tests/integration/components/phone-input-test.js
Labels: bug

#13 Create a country attribute
  addon/components/phone-input.js
  tests/integration/components/phone-input-test.js
Labels: bug

#15 Upgrade intl-tel-input from v14.0.3 to v14.0.6
  package.json
  yarn.lock
Labels: dependencies

#9 Allow for prepended production assets
  addon/services/phone-input.js
  tests/dummy/app/pods/docs/installation/template.md
  tests/dummy/config/environment.js
  tests/unit/services/phone-input-test.js
Labels: bug
