Repository qonto/ember-phone-input, pull requests merged in 2019-04, with the labels that each got.

#58 Update README to add ember-observer score
  README.md
Labels: documentation

#59 Update import naming in the documentation
  tests/dummy/app/pods/docs/lazy-loading/template.md
Labels: documentation

#57 Make sure correct path is used for intl-tel-input assets
  index.js
Labels: bug

#60 Update testing scenarios
  .travis.yml
  config/ember-try.js
  package.json
  yarn.lock
Labels: internal

#61 Make sure valid check updates when country changes
  addon/components/phone-input.js
  tests/integration/components/phone-input-test.js
Labels: bug

#65 Do not bind eventListener callback
  addon/components/phone-input.js
Labels: internal
