Repository qonto/ember-phone-input, pull requests merged in 2019-11, with the labels that each got.

#148 📝 add pull request template
  docs/pull_request_template.md
Labels: documentation

#151 Replace custom script loading code with `ember-auto-import`
  addon/components/phone-input.js
  addon/services/phone-input.js
  addon/utils/load-script.js
  index.js
  package.json
  tests/integration/components/phone-input-test.js
  tests/unit/services/phone-input-test.js
  yarn.lock
Labels: enhancement

#153 prettier: Set `semi: true`
  .prettierrc.js
  addon/components/phone-input.js
  addon/services/phone-input.js
  app/components/phone-input.js
  app/services/phone-input.js
  config/addon-docs.js
  config/deploy.js
  config/ember-try.js
  config/environment.js
  config/release.js
  ember-cli-build.js
  index.js
  testem.js
  tests/dummy/app/app.js
  tests/dummy/app/pods/application/route.js
  tests/dummy/app/pods/docs/components/phone-input/action-handling/component.js
  tests/dummy/app/pods/docs/components/phone-input/all-options/component.js
  tests/dummy/app/pods/docs/route.js
  tests/dummy/app/resolver.js
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/integration/components/phone-input-test.js
  tests/test-helper.js
Labels: internal

#134 [FEATURE] Add allowDropdown option
  addon/components/phone-input.js
  tests/dummy/app/pods/docs/components/phone-input/all-options/component.js
  tests/dummy/app/pods/docs/components/phone-input/all-options/template.hbs
  tests/integration/components/phone-input-test.js
Labels: enhancement

#154 Fix option lazyLoad: false
  addon/components/phone-input.js
  index.js
  package.json
  tests/integration/components/phone-input-test.js
Labels: bug

#157 Move script loading when `lazyLoad:false`
  addon/instance-initializers/phone-input.js
  addon/services/phone-input.js
  app/instance-initializers/phone-input.js
Labels: bug
