Repository qonto/ember-phone-input, pull requests merged in 2021-09, with the labels that each got.

#362 Drop support for ember@3.12
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
Labels: breaking

#367 fix(documentation): Set application-template-wrapper to true
  package.json
  tests/dummy/config/optional-features.json
Labels: documentation

#355 [refactor] use `this.element` directly
  addon/components/phone-input.js
Labels: bug

#371 Remove Node 10 & 11 from the package.json file
  package.json
Labels: bug
